set nocompatible
set guioptions-=T
set vb t_vb=
set ruler
set nohls
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set showmatch
set vb t_vb=
set ruler
set nohls
set incsearch
set virtualedit=all
set bs=2
set syntax=on