#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Configures the default subnet for containers.

    Examples:
        $(basename "$0") config container subnet 10.1.0.0/24

    host
    ---------
    Description:
        Configures the Tredly host.

    Subcommands:
        network - configures the given interface with ip address and gateway

    Examples:
        $(basename "$0") config host network em0 192.168.150.20/24 192.168.156.254
        $(basename "$0") config host gateway 192.168.150.254
        $(basename "$0") config host hostname myhost

"

case "${_SUBCOMMANDS[0]}" in
    container)
        case "${_SUBCOMMANDS[1]}" in
            subnet)
                tredly-host config ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
            ;;
            *)
                exit_with_error "Unknown config container command '${_SUBCOMMANDS[1]}'"
            ;;
        esac
    ;;
    firewall)
        case "${_SUBCOMMANDS[1]}" in
            addAPIwhitelist)
                tredly-host config ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
            ;;
            *)
                exit_with_error "Unknown config firewall command '${_SUBCOMMANDS[1]}'"
            ;;
        esac
    ;;
    host)
        case "${_SUBCOMMANDS[1]}" in
            gateway)
                tredly-host config ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
            ;;
            hostname)
                tredly-host config ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
            ;;
            network)
                tredly-host config ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
            ;;
            *)
                exit_with_error "Unknown config host command '${_SUBCOMMANDS[1]}'"
            ;;
        esac
    ;;
    *)
        exit_with_error "Unknown config command '${_SUBCOMMANDS[0]}'"
    ;;
esac
