#!/usr/bin/env bash

show_help "list -- Lists containers.

Examples:

    $(basename "$0") list containers --sort=uuid
    $(basename "$0") list partition
    $(basename "$0") list partition <partitionname>

Options:
    -h|--help|--usage  Displays this help text"

case "${_SUBCOMMANDS[0]}" in
    containers)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 3 ]]; then
            exit_with_error "Too many arguments received."
        fi

        # list the containers
        list_containers "${_SUBCOMMANDS[1]}" "${_SUBCOMMANDS[2]}"

    ;;
    partition)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 2 ]]; then
            exit_with_error "Too many arguments received."
        fi

        partition_list "${_SUBCOMMANDS[1]}"
    ;;
    partitions)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 1 ]]; then
            exit_with_error "Too many arguments received."
        fi

        partition_list
    ;;
    *)
        exit_with_error "Unknown list command \"${_SUBCOMMANDS[0]}\""
    ;;
esac

echo "--------------------"
