#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Replaces a container with the one specified by Tredlyfile.
        This command attempts to find a container to replace. If no container
        to replace was found, the new container is created anyway.

    Options:
        --path=          Provide an alternate path to a Tredlyfile
        --containerName= Override the container name
        --ip4_addr=      Manually specify the networking details for the new
                         container. Format: <interface>|<ip4 address>/<cidr>

    Examples:
        $(basename "$0") replace container customer1 --path=/path/to/container
"

case "${_SUBCOMMANDS[0]}" in
    container)
        tredly-build replace ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    *)
        exit_with_error "Unknown replace command '${_SUBCOMMANDS[0]}'"
    ;;
esac
