#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Starts an already created container.

    Options:
        --ip4_addr=      Manually specify the networking details for this
                         container. Format: <interface>|<ip4 address>/<cidr>

    Examples:
        $(basename "$0") start container xYH2KnI8
        $(basename "$0") start container xYH2KnI8 --ip4_addr=em0|192.168.0.5/24
"

case "${_SUBCOMMANDS[0]}" in
    container)
        tredly-build start ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    *)
        exit_with_error "Unknown create start \"${_SUBCOMMANDS[0]}\""
    ;;
esac
