#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Stops a running container.

    Examples:
        $(basename "$0") stop container xYH2KnI8

    containers <partitionname>
    ---------
    Description:
        Stops all running containers. If partitionname is given then only
        the containers within that partition will be stopped.

    Examples:
        $(basename "$0") stop containers
        $(basename "$0") stop containers mypartition
"

case "${_SUBCOMMANDS[0]}" in
    container)
        tredly-build stop ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    containers)
        tredly-build stop ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    *)
        exit_with_error "Unknown stop command \"${_SUBCOMMANDS[0]}\""
    ;;
esac
