#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Stops a running container.

    Examples:
        $(basename "$0") stop container xYH2KnI8
"

case "${_SUBCOMMANDS[0]}" in
    container)
        tredly-build stop ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    *)
        exit_with_error "Unknown stop command \"${_SUBCOMMANDS[0]}\""
    ;;
esac
