#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Validates a Tredlyfile.

    Options:
        --path=         Provide an alternate path to a Tredlyfile

    Examples:
        $(basename "$0") validate container
        $(basename "$0") validate container --path=/path/to/container
"

case "${_SUBCOMMANDS[0]}" in
    container)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 1 ]]; then
            exit_with_error "Too many arguments received."
        fi

        # use tredly build to validate
        tredly-build validate container ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}
    ;;
    *)
        exit_with_error "Unknown validate command '${_SUBCOMMANDS[0]}'"
    ;;
esac
