#!/usr/bin/env bash

# commands require running as root
cmn_assert_running_as_root

show_help "Available Commands:
    container
    ---------
    Description:
        Validates a Container's Tredlyfile.

    Options:
        --location=         Provide an alternate path to a Tredlyfile

    Examples:
        $(basename "$0") validate container
        $(basename "$0") validate container --location=/path/to/container
"

case "${_SUBCOMMANDS[0]}" in
    container)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 1 ]]; then
            exit_with_error "Too many arguments received."
        fi

        # use tredly validate to validate
        tredly-validate validate ${_SUBCOMMANDS[@]} ${_ENTIREFLAGS[@]}

        exit $?
    ;;
    *)
        exit_with_error "Unknown validate command '${_SUBCOMMANDS[0]}'"
    ;;
esac
