#!/usr/bin/env bash

# Sanity checks - make sure packages we need are installed
check_for_zfs

show_help "console -- Provides a shell within the given container.

Options:
    -h|--help|--usage  Displays this help text
Examples:
    $(basename "$0") console cf4c225f"

container_console "${2}"
