#!/usr/bin/env bash

# Sanity checks - make sure packages we need are installed
check_for_zfs

show_help "list -- Lists containers.

Examples:

    $(basename "$0") list containers --sort=uuid
    $(basename "$0") list partition
    $(basename "$0") list partition <partitionname>

Options:
    -s <jid|uuid|state|name|ip4|storage|created>  Sorts results by relevant column.
    -h|--help|--usage  Displays this help text"

case "${_SUBCOMMANDS[0]}" in
    containers)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 3 ]]; then
            exit_with_error "Too many arguments received."
        fi

        # list the containers
        list_containers "${_SUBCOMMANDS[1]}" "${_SUBCOMMANDS[2]}"

    ;;
    partitions)
        # validation
        if [[ ${#_SUBCOMMANDS[@]} -gt 1 ]]; then
            exit_with_error "Too many arguments received."
        fi

        partition_list
    ;;
    *)
        exit_with_error "Unknown list command \"${_SUBCOMMANDS[0]}\""
    ;;
esac

echo "--------------------"
